version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /usr/src/tutorial
    command:
      - "gunicorn"
      - "tutorial.wsgi:application"
      - "--reload"
      - "--bind"
      - "0.0.0.0:8000"
    env_file: 
      - containers/app/app.env
    environment:
      - PROJECT_DIR=/usr/src/tutorial/tutorial
    volumes:
      - type: bind
        source: ./tutorial
        target: /usr/src/tutorial
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    env_file: 
      - containers/db/db.env
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
      
volumes:
  db-data:
