version: "3.8"

services:
  develop:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile.develop
    user: "${UID:-1000}:${GID:-1000}"
    env_file: 
      - containers/app/app.env
    depends_on:
      - db
      
volumes:
  db-data:
